void test(void);
void help(void);
void hello(void);
void reboot(void);
void ls(void);
void cat(void);
void svc(void);
void timer(void);
void setTimeout(char [][16]);
int palloc(int size);
void freepage(int index);
void *malloc(int size);
void free(void *addr);
void reserve(int , int);
void async_IO(void);
void test_kernel(void);
